version: "3.9"
services:
  app:
    build: .
    env_file: .env
    environment:
      - SE_EPHE_PATH=/ephe
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./ephe:/ephe:ro
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
