version: "3.9"
services:
  engine:
    build: .
    environment:
      - SE_EPHE_PATH=/app/ephe
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - redis
    volumes:
      - ephe-vol:/app/ephe

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]

volumes:
  ephe-vol:
