version: "3.9"

services:
  engine:
    build: .
    environment:
      - SE_EPHE_PATH=/app/ephe
      - REDIS_URL=redis://redis:6379/0
      # İsteğe bağlı:
      # - RATE_LIMIT_DISABLED=0
      # - OPENAPI_ENABLED=false
    depends_on:
      - redis
    volumes:
      - ephe-vol:/app/ephe
    # Dokploy domain için burada port açmaya GEREK YOK.
    # Domain ekranında Container Port olarak 8000 seçeceksin.

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    # Güvenlik için dış port AÇMA (ports satırı YOK).

volumes:
  ephe-vol:
